name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: malaka
        password: ${{ secrets.DIGI_PASS }}
        port: 22
        script: |
          cd simple-cicd
          git pull
          yarn build
          pm2 restart all